//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serverr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoursesTbl()
        {
            this.Registration = new HashSet<Registration>();
        }
    
        public short IdCourse { get; set; }
        public Nullable<short> IdTeacher { get; set; }
        public short IdSubject { get; set; }
        public short DayInWeekC { get; set; }
        public Nullable<System.TimeSpan> FromHourC { get; set; }
        public Nullable<System.TimeSpan> UntilHourC { get; set; }
        public short MinStudents { get; set; }
        public short MaxStudents { get; set; }
        public Nullable<short> IdTypeCourse { get; set; }
        public short AmountHour { get; set; }
        public short PricePerHour { get; set; }
        public short AmountStudentRegistration { get; set; }
        public short OpenCourse { get; set; }
    
        public virtual SubjectTbl SubjectTbl { get; set; }
        public virtual TeacherTbl TeacherTbl { get; set; }
        public virtual TypeCourseTbl TypeCourseTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registration { get; set; }
    }
}
