//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serverr.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FurtherTraining3Entities4 : DbContext
    {
        public FurtherTraining3Entities4()
            : base("name=FurtherTraining3Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailableTeacherTbl> AvailableTeacherTbl { get; set; }
        public virtual DbSet<Connect> Connect { get; set; }
        public virtual DbSet<CoursesTbl> CoursesTbl { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<StudentsTbl> StudentsTbl { get; set; }
        public virtual DbSet<StudentWaitToRegistration> StudentWaitToRegistration { get; set; }
        public virtual DbSet<SubjectOfTeacherTbl> SubjectOfTeacherTbl { get; set; }
        public virtual DbSet<SubjectTbl> SubjectTbl { get; set; }
        public virtual DbSet<TeacherTbl> TeacherTbl { get; set; }
        public virtual DbSet<TypeCourseTbl> TypeCourseTbl { get; set; }
    }
}
