//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serverr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectOfTeacherTbl
    {
        public short IdSubjectOfTeacher { get; set; }
        public short IdTeacher { get; set; }
        public short IdSubject { get; set; }
        public string Comments { get; set; }
    
        public virtual SubjectTbl SubjectTbl { get; set; }
        public virtual TeacherTbl TeacherTbl { get; set; }
    }
}
