//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serverr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeacherTbl()
        {
            this.AvailableTeacherTbl = new HashSet<AvailableTeacherTbl>();
            this.CoursesTbl = new HashSet<CoursesTbl>();
            this.SubjectOfTeacherTbl = new HashSet<SubjectOfTeacherTbl>();
        }
    
        public short IdTeacher { get; set; }
        public string FirstNameT { get; set; }
        public string LastNameT { get; set; }
        public string AddressT { get; set; }
        public string PhoneT { get; set; }
        public string EmailT { get; set; }
        public string TzT { get; set; }
        public int Price { get; set; }
        public short Prefer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailableTeacherTbl> AvailableTeacherTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoursesTbl> CoursesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectOfTeacherTbl> SubjectOfTeacherTbl { get; set; }
    }
}
